/**
 * author Anushka Isuru Lakmal
 * created on 14-02-2025-11h-34m
 * copyright 2025
 */

//machines
export const FETCH_ALL_CLIENTS = 'FETCH_ALL_CLIENTS'
export const FETCH_CLIENT_BY_ID = 'FETCH_CLIENT_BY_ID'
export const ADD_CLIENT = 'ADD_CLIENT'
export const DELETE_CLIENT = 'DELETE_CLIENT'
export const UPDATE_CLIENT_BY_ID = 'UPDATE_CLIENT_BY_ID'
// export const UPDATE_CLIENT_STATUS = 'UPDATE_CLIENT_STATUS'

//machines
export const FETCH_ALL_MACHINES = 'FETCH_ALL_MACHINES'
export const FETCH_MACHINE_BY_ID = 'FETCH_MACHINE_BY_ID'
export const ADD_MACHINE = 'ADD_MACHINE'
export const DELETE_MACHINE = 'DELETE_MACHINE'
export const UPDATE_MACHINE_BY_ID = 'UPDATE_MACHINE_BY_ID'
export const UPDATE_MACHINE_STATUS = 'UPDATE_MACHINE_STATUS'

//items
export const FETCH_ALL_ITEMS = 'FETCH_ALL_ITEMS'
export const FETCH_ITEM_BY_ID = 'FETCH_ITEM_BY_ID'
export const FETCH_ITEM_BY_CLIENT = 'FETCH_ITEM_BY_CLIENT'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_ITEM_BY_ID = 'UPDATE_ITEM_BY_ID'

//items-types
export const FETCH_ALL_ITEM_TYPES = 'FETCH_ALL_ITEM_TYPES'
export const FETCH_ITEM_TYPE_BY_ID = 'FETCH_ITEM_TYPE_BY_ID'
export const ADD_ITEM_TYPE = 'ADD_ITEM_TYPE'
export const DELETE_ITEM_TYPE = 'DELETE_ITEM_TYPE'
export const UPDATE_ITEM_TYPE_BY_ID = 'UPDATE_ITEM_TYPE_BY_ID'
